---
-
  blog: "orbertgame.tumblr.com"
  description: |
    Swing Orbert around moons and avoid the dreaded White Walls of Devastation.
    100 levels will challenge even the most dexterous screen tapper.
    It's wonderfully fun, with criminally simple controls (just tap!) and the most charming unshaven shuttle you'll ever clap eyes on.
    <br /><br />
    Featuring flippin' fun physics, loads of levels (from "piece of cake" to "piece of cruel impossibility"), and three colours!
  name: Orbert
  platforms:
    "Google Play,": "https://play.google.com/store/apps/details?id=com.RebelHippo.Orbert"
    "Blackberry": "https://appworld.blackberry.com/webstore/content/50003906/?lang=en"
  release: "April 1, 2014"
  website: "http://www.playorbert.com"
  video: "https://www.youtube.com/embed/H8DMQPQ2hzU"

-
  blog: "lumospowered.tumblr.com"
  description: |
    Lumos is an online game service provider offering analytics, diagnostics, and common social functionality services.
    Studios can make informed decisions about what platforms to target, where to focus their development efforts, and help players connect with friends within their games.
  name: Lumos
  platforms:
    "Web": "https://www.lumospowered.com"
  release: "July 1, 2011"
  website: "https://www.lumospowered.com"
  video: "https://www.youtube.com/embed/l4FKrllkUnE"

-
  blog: "justpretendgame.tumblr.com"
  description: |
    Brave the bizarre world of a child's imagination in this top-down open world roguelike adventure.
    Explore vast procedurally generated environments, avoid dangerous traps, find helpful treasures, discover secrets, defeat fantastic enemies, and challenge ridiculous bosses.
    <br />
    <br />
    Inspired by the classic <a href="https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_A_Link_to_the_Past">Legend of Zelda: A Link to the Past</a> and roguelike greats such as <a href="https://en.wikipedia.org/wiki/Spelunky">Spelunky</a>.
  name: Just Pretend
  platforms:
    "TBA": "#"
  release: "TBA"
  website: ""
